-- =========================================================================
-- ESQUEMA COMPLETO FINAL - SISTEMA ARRAIAL ODONTO (TESTES / STAGING)
-- =========================================================================

-- 1. TIPOS PERSONALIZADOS (ENUMS)
CREATE TYPE public.appointment_status_enum AS ENUM ('Scheduled', 'Confirmed', 'Completed', 'Cancelled', 'No-Show', 'Pending Confirmation', 'Patient Arrived');
CREATE TYPE public.certificate_type_enum AS ENUM ('attendance', 'medical_leave', 'fitness');
CREATE TYPE public.expense_category_enum AS ENUM ('rent', 'utilities', 'supplies', 'equipment', 'salary', 'marketing', 'maintenance', 'other');
CREATE TYPE public.expense_status_enum AS ENUM ('pending', 'paid');
CREATE TYPE public.goal_status_enum AS ENUM ('active', 'completed', 'cancelled');
CREATE TYPE public.installment_plan_status_enum AS ENUM ('active', 'completed', 'cancelled');
CREATE TYPE public.installment_status_enum AS ENUM ('pending', 'paid', 'overdue', 'cancelled');
CREATE TYPE public.payment_method_enum AS ENUM ('cash', 'credit_card', 'debit_card', 'pix', 'bank_transfer', 'insurance', 'boleto');
CREATE TYPE public.payment_status_enum AS ENUM ('pending', 'completed', 'cancelled', 'refunded', 'partial');
CREATE TYPE public.prescription_type_enum AS ENUM ('simple', 'controlled', 'special');
CREATE TYPE public.specialization_enum AS ENUM ('Cirurgião-Dentista', 'Ortodontista');
CREATE TYPE public.tooth_face_enum AS ENUM ('oclusal', 'mesial', 'distal', 'vestibular', 'lingual', 'incisal');
CREATE TYPE public.tooth_status_enum AS ENUM ('higido', 'cariado', 'obturado', 'extraido', 'tratamento_canal', 'coroa', 'implante', 'ausente', 'fratura');
CREATE TYPE public.transaction_type_enum AS ENUM ('payment', 'refund', 'discount');
CREATE TYPE public.treatment_plan_item_status_enum AS ENUM ('pending', 'in_progress', 'completed', 'cancelled', 'awaiting_payment');
CREATE TYPE public.treatment_plan_status_enum AS ENUM ('awaiting_payment', 'approved', 'in_progress', 'completed', 'cancelled');

-- 2. CRIAÇÃO DAS TABELAS BÁSICAS E DE NEGÓCIO (EM ESTADO FINAL DE PRODUÇÃO)

CREATE TABLE public.patients (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    full_name text NOT NULL,
    contact_phone text NOT NULL,
    cpf text,
    birth_date date,
    medical_history_notes text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.professionals (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    full_name text NOT NULL,
    specialization public.specialization_enum NOT NULL,
    user_id uuid,
    contact_phone text,
    clinic_name text,
    clinic_cnpj text,
    clinic_phone text,
    clinic_address text,
    professional_registry text,
    registry_uf text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.staff_profiles (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    role text NOT NULL,
    user_id uuid
);

CREATE TABLE public.treatments (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    treatment_name text NOT NULL,
    default_duration_minutes integer NOT NULL DEFAULT 30,
    cost numeric,
    description text
);

CREATE TABLE public.appointments (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id),
    professional_id uuid REFERENCES public.professionals(id),
    treatment_id uuid REFERENCES public.treatments(id),
    treatment_plan_item_id uuid, -- Relacionamento circular, fkey adicionada ao final
    appointment_start_time timestamp with time zone NOT NULL,
    appointment_end_time timestamp with time zone NOT NULL,
    status public.appointment_status_enum NOT NULL DEFAULT 'Scheduled',
    notes text,
    is_squeeze_in boolean DEFAULT false,
    confirmation_sent_at timestamp with time zone,
    last_reminder_sent_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.waiting_list (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id) NOT NULL,
    professional_id uuid REFERENCES public.professionals(id) NOT NULL,
    treatment_id uuid REFERENCES public.treatments(id),
    notes text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.communication_logs (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id),
    appointment_id uuid REFERENCES public.appointments(id),
    direction text NOT NULL,
    communication_content text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.professional_schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_id uuid REFERENCES public.professionals(id),
    day_of_week integer NOT NULL,
    start_time text NOT NULL,
    end_time text NOT NULL
);

CREATE TABLE public.patient_documents (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id) NOT NULL,
    file_name text NOT NULL,
    file_path text NOT NULL,
    file_size integer,
    mime_type text,
    uploaded_by uuid,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.expenses (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    description text NOT NULL,
    amount numeric NOT NULL,
    due_date date NOT NULL,
    payment_date date,
    category public.expense_category_enum NOT NULL,
    status public.expense_status_enum NOT NULL DEFAULT 'pending',
    notes text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.treatment_plans (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id) NOT NULL,
    professional_id uuid REFERENCES public.professionals(id) NOT NULL,
    title text,
    status public.treatment_plan_status_enum NOT NULL DEFAULT 'awaiting_payment',
    total_cost numeric,
    notes text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.treatment_plan_items (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    treatment_plan_id uuid REFERENCES public.treatment_plans(id) NOT NULL,
    procedure_description text NOT NULL,
    tooth_number integer,
    estimated_cost numeric,
    status public.treatment_plan_item_status_enum NOT NULL DEFAULT 'pending',
    priority integer,
    notes text,
    treatment_id uuid REFERENCES public.treatments(id),
    appointment_id uuid REFERENCES public.appointments(id),
    scheduled_date timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Adiciona a chave estrangeira circular na tabela appointments
ALTER TABLE public.appointments 
    ADD CONSTRAINT appointments_treatment_plan_item_id_fkey 
    FOREIGN KEY (treatment_plan_item_id) REFERENCES public.treatment_plan_items(id);

CREATE TABLE public.odontogram_records (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id) NOT NULL,
    tooth_number integer NOT NULL,
    status public.tooth_status_enum NOT NULL DEFAULT 'higido',
    notes text,
    last_updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_updated_by uuid
);

CREATE TABLE public.tooth_procedures (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id) NOT NULL,
    professional_id uuid REFERENCES public.professionals(id),
    tooth_number integer NOT NULL,
    faces public.tooth_face_enum[],
    procedure_type text NOT NULL,
    procedure_date date NOT NULL DEFAULT CURRENT_DATE,
    status_before public.tooth_status_enum,
    status_after public.tooth_status_enum NOT NULL,
    material_used text,
    notes text,
    status text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.payments (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id) NOT NULL,
    treatment_plan_id uuid REFERENCES public.treatment_plans(id),
    subtotal numeric NOT NULL,
    discount_type text,
    discount_value numeric,
    discount_amount numeric NOT NULL DEFAULT 0,
    total_amount numeric NOT NULL,
    total_installments integer NOT NULL DEFAULT 1,
    installment_number integer NOT NULL DEFAULT 1,
    payment_date timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    registered_by uuid NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.payment_entries (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    payment_id uuid REFERENCES public.payments(id) NOT NULL,
    payment_method public.payment_method_enum NOT NULL,
    amount numeric NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.payment_splits (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    payment_id uuid REFERENCES public.payments(id) NOT NULL,
    professional_id uuid REFERENCES public.professionals(id) NOT NULL,
    amount numeric NOT NULL,
    percentage numeric NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    payment_date timestamp with time zone,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.expense_installments (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    expense_id uuid REFERENCES public.expenses(id) NOT NULL,
    installment_number integer NOT NULL,
    amount numeric NOT NULL,
    due_date date NOT NULL,
    status public.expense_status_enum NOT NULL DEFAULT 'pending',
    payment_date date,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.financial_transactions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id),
    amount numeric NOT NULL,
    transaction_type public.transaction_type_enum NOT NULL,
    payment_method public.payment_method_enum,
    registered_by uuid NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.installment_plans (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id) NOT NULL,
    total_amount numeric NOT NULL,
    installments_count integer NOT NULL,
    status public.installment_plan_status_enum NOT NULL DEFAULT 'active',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.installment_payments (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    plan_id uuid REFERENCES public.installment_plans(id) NOT NULL,
    installment_number integer NOT NULL,
    amount numeric NOT NULL,
    due_date date NOT NULL,
    status public.installment_status_enum NOT NULL DEFAULT 'pending',
    payment_date timestamp with time zone,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.financial_goals (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    target_amount numeric NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status public.goal_status_enum NOT NULL DEFAULT 'active',
    current_amount numeric NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.prescriptions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id) NOT NULL,
    professional_id uuid REFERENCES public.professionals(id) NOT NULL,
    appointment_id uuid REFERENCES public.appointments(id),
    prescription_type public.prescription_type_enum NOT NULL,
    is_template boolean DEFAULT false,
    template_name text,
    general_instructions text,
    signature_hash text,
    pdf_file_path text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.prescription_items (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    prescription_id uuid REFERENCES public.prescriptions(id) NOT NULL,
    medication_name text NOT NULL,
    dosage text NOT NULL,
    frequency text NOT NULL,
    duration text NOT NULL,
    instructions text,
    item_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.medical_certificates (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id uuid REFERENCES public.patients(id) NOT NULL,
    professional_id uuid REFERENCES public.professionals(id) NOT NULL,
    appointment_id uuid REFERENCES public.appointments(id),
    certificate_type public.certificate_type_enum NOT NULL,
    reason text NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone,
    days_count integer,
    cid_10_code text,
    additional_notes text,
    signature_hash text,
    pdf_file_path text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.prescription_templates (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    template_name text NOT NULL,
    description text,
    prescription_type public.prescription_type_enum NOT NULL,
    general_instructions text,
    professional_id uuid REFERENCES public.professionals(id),
    is_shared boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.prescription_template_items (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    template_id uuid REFERENCES public.prescription_templates(id) NOT NULL,
    medication_name text NOT NULL,
    dosage text NOT NULL,
    frequency text NOT NULL,
    duration text NOT NULL,
    instructions text,
    item_order integer NOT NULL DEFAULT 0
);

-- =========================================================================
-- HABILITANDO SEGURANÇA RLS NAS TABELAS
-- =========================================================================

ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.professionals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.waiting_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.communication_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.professional_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatment_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.treatment_plan_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.odontogram_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tooth_procedures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_splits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_installments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installment_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installment_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prescriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prescription_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prescription_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prescription_template_items ENABLE ROW LEVEL SECURITY;
